/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FilesRouteImport } from './routes/files'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as ChronicleRouteImport } from './routes/chronicle'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as ApiRahVisionTestRouteImport } from './routes/api/rah-vision-test'
import { Route as ApiRahHealthRouteImport } from './routes/api/rah-health'
import { Route as ApiRahChatRouteImport } from './routes/api/rah-chat'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ChronicleRoute = ChronicleRouteImport.update({
  id: '/chronicle',
  path: '/chronicle',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const ApiRahVisionTestRoute = ApiRahVisionTestRouteImport.update({
  id: '/api/rah-vision-test',
  path: '/api/rah-vision-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRahHealthRoute = ApiRahHealthRouteImport.update({
  id: '/api/rah-health',
  path: '/api/rah-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRahChatRoute = ApiRahChatRouteImport.update({
  id: '/api/rah-chat',
  path: '/api/rah-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/approvals': typeof ApprovalsRoute
  '/automations': typeof AutomationsRoute
  '/chronicle': typeof ChronicleRoute
  '/connections': typeof ConnectionsRoute
  '/devices': typeof DevicesRoute
  '/files': typeof FilesRoute
  '/history': typeof HistoryRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vision': typeof VisionRoute
  '/voice': typeof VoiceRoute
  '/api/rah-chat': typeof ApiRahChatRoute
  '/api/rah-health': typeof ApiRahHealthRoute
  '/api/rah-vision-test': typeof ApiRahVisionTestRoute
  '/projects/$id': typeof ProjectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/approvals': typeof ApprovalsRoute
  '/automations': typeof AutomationsRoute
  '/chronicle': typeof ChronicleRoute
  '/connections': typeof ConnectionsRoute
  '/devices': typeof DevicesRoute
  '/files': typeof FilesRoute
  '/history': typeof HistoryRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vision': typeof VisionRoute
  '/voice': typeof VoiceRoute
  '/api/rah-chat': typeof ApiRahChatRoute
  '/api/rah-health': typeof ApiRahHealthRoute
  '/api/rah-vision-test': typeof ApiRahVisionTestRoute
  '/projects/$id': typeof ProjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/approvals': typeof ApprovalsRoute
  '/automations': typeof AutomationsRoute
  '/chronicle': typeof ChronicleRoute
  '/connections': typeof ConnectionsRoute
  '/devices': typeof DevicesRoute
  '/files': typeof FilesRoute
  '/history': typeof HistoryRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vision': typeof VisionRoute
  '/voice': typeof VoiceRoute
  '/api/rah-chat': typeof ApiRahChatRoute
  '/api/rah-health': typeof ApiRahHealthRoute
  '/api/rah-vision-test': typeof ApiRahVisionTestRoute
  '/projects/$id': typeof ProjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/approvals'
    | '/automations'
    | '/chronicle'
    | '/connections'
    | '/devices'
    | '/files'
    | '/history'
    | '/memory'
    | '/onboarding'
    | '/privacy'
    | '/projects'
    | '/settings'
    | '/sitemap.xml'
    | '/vision'
    | '/voice'
    | '/api/rah-chat'
    | '/api/rah-health'
    | '/api/rah-vision-test'
    | '/projects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/approvals'
    | '/automations'
    | '/chronicle'
    | '/connections'
    | '/devices'
    | '/files'
    | '/history'
    | '/memory'
    | '/onboarding'
    | '/privacy'
    | '/projects'
    | '/settings'
    | '/sitemap.xml'
    | '/vision'
    | '/voice'
    | '/api/rah-chat'
    | '/api/rah-health'
    | '/api/rah-vision-test'
    | '/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/approvals'
    | '/automations'
    | '/chronicle'
    | '/connections'
    | '/devices'
    | '/files'
    | '/history'
    | '/memory'
    | '/onboarding'
    | '/privacy'
    | '/projects'
    | '/settings'
    | '/sitemap.xml'
    | '/vision'
    | '/voice'
    | '/api/rah-chat'
    | '/api/rah-health'
    | '/api/rah-vision-test'
    | '/projects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AutomationsRoute: typeof AutomationsRoute
  ChronicleRoute: typeof ChronicleRoute
  ConnectionsRoute: typeof ConnectionsRoute
  DevicesRoute: typeof DevicesRoute
  FilesRoute: typeof FilesRoute
  HistoryRoute: typeof HistoryRoute
  MemoryRoute: typeof MemoryRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VisionRoute: typeof VisionRoute
  VoiceRoute: typeof VoiceRoute
  ApiRahChatRoute: typeof ApiRahChatRoute
  ApiRahHealthRoute: typeof ApiRahHealthRoute
  ApiRahVisionTestRoute: typeof ApiRahVisionTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chronicle': {
      id: '/chronicle'
      path: '/chronicle'
      fullPath: '/chronicle'
      preLoaderRoute: typeof ChronicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/api/rah-vision-test': {
      id: '/api/rah-vision-test'
      path: '/api/rah-vision-test'
      fullPath: '/api/rah-vision-test'
      preLoaderRoute: typeof ApiRahVisionTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rah-health': {
      id: '/api/rah-health'
      path: '/api/rah-health'
      fullPath: '/api/rah-health'
      preLoaderRoute: typeof ApiRahHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rah-chat': {
      id: '/api/rah-chat'
      path: '/api/rah-chat'
      fullPath: '/api/rah-chat'
      preLoaderRoute: typeof ApiRahChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ApprovalsRoute: ApprovalsRoute,
  AutomationsRoute: AutomationsRoute,
  ChronicleRoute: ChronicleRoute,
  ConnectionsRoute: ConnectionsRoute,
  DevicesRoute: DevicesRoute,
  FilesRoute: FilesRoute,
  HistoryRoute: HistoryRoute,
  MemoryRoute: MemoryRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VisionRoute: VisionRoute,
  VoiceRoute: VoiceRoute,
  ApiRahChatRoute: ApiRahChatRoute,
  ApiRahHealthRoute: ApiRahHealthRoute,
  ApiRahVisionTestRoute: ApiRahVisionTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
